config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'rooms/index'
  get 'rooms/new'
  get 'rooms/show/:id' => 'rooms#show', as: :rooms_show
  post 'rooms/create' => 'rooms#create'
  root to: "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @newRoom = Room.new
  end

  def show
  end

  def create
    @room = Room.new(params[:room].permit(:title))
    @room.save
    redirect_to rooms_new_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Classroom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%#= link_to image_tag class: :logo, root_path %>
            CLASS ROOM
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "クラスのお知らせ", rooms_new_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © 2021 S.S</p>
    </footer>
  </body>
</html>

app/views/rooms/delete.html.erb
<%#= link_to '[削除]', rooms_delete_path(room.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>

app/views/rooms/index.html.erb
<main class="main">
  <div class="inner">

    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to current_user.nickname + "さん", "#", class: :greeting__link%>
      </div>
    <% end %>

    <div class="card__wrapper">
     <%#= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/rooms/new.html.erb
<h1>トピック一覧</h1>
<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.title, rooms_show_path(room.id) %></li>
  <% end %>
</ul>

<h1>トピック新規登録</h1>
<%= form_for @newRoom, :url => {:action => 'create'} do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>